Feature/boleto holmes
starkbank/sdk-php pull request #19
Opened 2020-09-25 22:32 UTC by vidalstark

2020-09-27 13:27 UTC, cdottori-stark requested changes

2020-09-27 13:27 UTC, cdottori-stark commented on src/boletoHolmes/boletoHolmes.php
> +        - status [string, default null]: current holmes status. ex: "pending" or "verified"
os status possíveis são "solving" e "solved"

2020-09-27 13:27 UTC, cdottori-stark commented on src/boletoHolmes/boletoHolmes.php
> +        - updated [datetime.datetime, default null]: latest update datetime for the holmes. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)
Acho que esses tipos e exemplos de created e updated são do python

2020-09-27 13:27 UTC, cdottori-stark commented on src/boletoHolmes/boletoHolmes.php
> +        - user [Project object]: Project object. Not necessary if starkbank.user was set before function call
String do python aqui, tem que usar o padrão do PHP

2020-09-27 13:27 UTC, cdottori-stark commented on src/boletoHolmes/boletoHolmes.php
> +        - before [datetime.date or string, default null] date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
exemplos e tipos de python de novo

2020-09-27 13:27 UTC, cdottori-stark commented on src/boletoHolmes/boletoHolmes.php
> +        - ids [list of strings, default null]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
nao sei se no resto das docstrings ta assim, mas é melhor chamar de array no PHP em vez de list

2020-09-27 13:27 UTC, cdottori-stark commented on src/boletoHolmes/boletoHolmes.php
> +        - user [Project object, default null]: Project object. Not necessary if starkbank.user was set before function call
docstring do python de novo

2020-09-27 13:27 UTC, cdottori-stark commented on src/boletoHolmes/log.php
> +        - created [datetime.datetime]: creation datetime for the log. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)
python de novo

2020-09-27 13:27 UTC, cdottori-stark commented on src/boletoHolmes/log.php
> +    Every time a BoletoHolmes entity is modified, a corresponding boletoholmes.Log
boletoHolmes.Log -> BoletoHolmes\Log

2020-09-27 13:27 UTC, cdottori-stark commented on src/boletoHolmes/log.php
> +        - before [datetime.date or string, default null] date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
python

2020-09-27 13:27 UTC, cdottori-stark commented on src/utils/api.php
> +            return API::lastName($resourceName) . "ies";
faltou cortar o y do final do $resourceName antes de colocar o íes

2020-09-27 13:27 UTC, cdottori-stark commented on tests/boletoHolmes.php
> +    }
Nao da pra pegar o example la do teste de boleto nao?

2020-09-27 13:27 UTC, cdottori-stark commented on tests/boletoHolmes.php
> +    }
Pode trocar o modificador de acesso se for necessário

2020-09-27 16:26 UTC, cdottori-stark requested changes
Faltou o README

2020-09-28 22:03 UTC, vidalstark commented on src/boletoHolmes/boletoHolmes.php
> +        - status [string, default null]: current holmes status. ex: "pending" or "verified"
OK

2020-09-28 22:16 UTC, vidalstark commented on src/boletoHolmes/boletoHolmes.php
> +        - updated [datetime.datetime, default null]: latest update datetime for the holmes. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)
Ok. Resolvido

2020-09-28 22:25 UTC, vidalstark commented on src/boletoHolmes/boletoHolmes.php
> +        - before [datetime.date or string, default null] date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
Ok. Resolvido

2020-09-28 22:30 UTC, vidalstark commented on src/boletoHolmes/boletoHolmes.php
> +        - user [Project object]: Project object. Not necessary if starkbank.user was set before function call
Ok. Resolvido.

2020-09-28 22:33 UTC, vidalstark commented on src/boletoHolmes/boletoHolmes.php
> +        - ids [list of strings, default null]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
Ok. Mudei no SDK inteiro

2020-09-28 22:33 UTC, vidalstark commented on src/boletoHolmes/boletoHolmes.php
> +        - user [Project object, default null]: Project object. Not necessary if starkbank.user was set before function call
Ok. Resolvido

2020-09-28 22:34 UTC, vidalstark commented on src/boletoHolmes/log.php
> +        - created [datetime.datetime]: creation datetime for the log. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)
Ok. Resolvido.

2020-09-28 22:44 UTC, vidalstark commented on src/boletoHolmes/log.php
> +    Every time a BoletoHolmes entity is modified, a corresponding boletoholmes.Log
Ok. Resolvido.

2020-09-28 22:45 UTC, vidalstark commented on src/boletoHolmes/log.php
> +        - before [datetime.date or string, default null] date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
Ok. Resolvido

2020-09-28 22:47 UTC, vidalstark commented on src/utils/api.php
> +            return API::lastName($resourceName) . "ies";
Ok. Resolvido.

2020-09-28 23:07 UTC, vidalstark commented on tests/boletoHolmes.php
> +    }
Beleza. Peguei

2020-10-28 21:18 UTC, cdottori-stark approved these changes

2020-10-28 21:20 UTC, merged