Page function to Boleto resource
starkbank/sdk-php pull request #48
Opened 2021-07-07 21:44 UTC by massaru-stark

2021-07-07 21:49 UTC, cdottori-stark requested changes

2021-07-07 21:49 UTC, cdottori-stark commented on tests/boleto.php
> +            $cursor = $response["cursor"];
Melhor usar o padrão do key.php aqui:

list($boletos, $cursor) = Boleto::page($options = ["limit" => 5, "cursor" => $cursor]);

2021-07-07 21:49 UTC, cdottori-stark commented on tests/boleto.php
> +            }
Esse teste era mais pra ver se a paginação automático nao ta loopando em falso, aqui pode deixar só os asserts de $boleto->id e tal

2021-07-07 21:49 UTC, cdottori-stark commented on src/utils/rest.php
> +        return array("page" => $entities, "cursor" => $cursor);
Melhor manter o padrão do key.php aqui:

return [$entities, $cursor];

2021-07-08 19:00 UTC, cdottori-stark requested changes

2021-07-08 19:00 UTC, cdottori-stark commented on src/invoice/log.php
> +
tenta por logo depois do query

2021-07-08 19:21 UTC, massaru-stark commented on src/boletoHolmes/boletoHolmes.php
> +    - user [Organization/Project object, default null]: Organization or Project object. Not necessary if StarkBank\Settings::setUser() was set before function call
Preciso arrumar a doc string do sdk-python também.

2021-07-08 19:52 UTC, cdottori-stark requested changes

2021-07-08 19:52 UTC, cdottori-stark commented on src/brcodePayment/log.php
> +    - brcodePaymentIds [array of strings, default null]: array of BrcodePayment ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
paymentIds

2021-07-08 19:52 UTC, cdottori-stark commented on src/brcodePayment/log.php
> +    - brcodePaymentIds [array of strings, default null]: array of BrcodePayment ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
paymentIds

2021-07-08 19:52 UTC, cdottori-stark commented on src/invoice/log.php
> +    - status [string, default null]: filter for status of retrieved objects. ex: "paid" or "registered"
tem esse nao

2021-07-08 19:52 UTC, cdottori-stark commented on src/transfer/log.php
> +    - cursor to retrieve the next page of Transfero\Log objects
Transferoooo\Log

2021-07-08 19:52 UTC, cdottori-stark commented on src/transfer/log.php
> +    - list of Transfero\Log objects with updated attributes
Transferoooo\Log

2021-07-08 19:52 UTC, cdottori-stark commented on src/utilityPayment/utilityPayment.php
> +    - ids [list of strings, default null]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
nao ta na mesma ordem do query, suspeito hahah

2021-07-08 19:52 UTC, cdottori-stark commented on src/workspace/workspace.php
> +     */
oops

2021-07-08 19:52 UTC, cdottori-stark commented on tests/workspace.php
> +        if (count($ids) == 0) {
acho que pode por != 4 aqui mesmo

2021-07-08 20:21 UTC, cdottori-stark requested changes

2021-07-08 20:21 UTC, cdottori-stark commented on src/utilityPayment/log.php
> +    - status [string, default null]: filter for status of retrieved objects. ex: "paid" or "registered"
não existe

2021-07-08 20:29 UTC, cdottori-stark approved these changes

2021-07-08 20:44 UTC, cdottori-stark approved these changes

2021-07-08 20:44 UTC, merged