Add PaymentPreview resource
starkbank/sdk-php pull request #52
Opened 2021-08-26 14:28 UTC by massaru-stark

2021-08-31 19:38 UTC, cdottori-stark requested changes

2021-08-31 19:38 UTC, cdottori-stark commented on README.md
> +array_push($previews, new PaymentPreview(["id" => "34191.09008 61207.727308 71444.640008 5 81310001234321"]));
credo, faz um array literal direto hahah

2021-08-31 19:38 UTC, cdottori-stark commented on README.md
> +$previews = PaymentPreview::create($previews);
pode por até aqui dentro do create direto, se achar melhor

2021-08-31 19:38 UTC, cdottori-stark commented on README.md
> +**Note**: Instead of using PaymentPreview objects, you can also pass each request element in dictionary format
Instead of using PaymentPreview objects, you can also pass each element directly in array format, without using the constructor

2021-08-31 19:38 UTC, cdottori-stark commented on src/brcodePreview/brcodePreview.php
> +        trigger_error(__METHOD__ . ' is deprecated, use PaymentPreview instead', E_USER_DEPRECATED);
Isso da raise ou só warning?

2021-08-31 19:38 UTC, cdottori-stark commented on src/brcodePreview/brcodePreview.php
> +        trigger_error(__METHOD__ . ' is deprecated, use PaymentPreview instead', E_USER_DEPRECATED);
Melhor colocar BrcodePreview em vez de __METHOD__ também

2021-08-31 19:38 UTC, cdottori-stark commented on src/init.php
> +require_once(__DIR__."/paymentPreview/paymentPreview.php");
essa linha nao deveria vir depois das outras dado que usa com conteúdo delas? se funcionou beleza, só estranhei mesmo

2021-08-31 19:38 UTC, cdottori-stark commented on src/paymentPreview/boletoPreview.php
> +use urlencode\urlencode;
precisa de urlencode mesmo?

2021-08-31 19:38 UTC, cdottori-stark commented on src/paymentPreview/brcodePreview.php
> +use urlencode\urlencode;
precisa de urlencode mesmo?

2021-08-31 19:38 UTC, cdottori-stark commented on src/paymentPreview/taxPreview.php
> +use urlencode\urlencode;
precisa desse urlencode?

2021-08-31 19:38 UTC, cdottori-stark commented on src/paymentPreview/utilityPreview.php
> +use urlencode\urlencode;
precisa desse urlencode?

2021-08-31 19:38 UTC, cdottori-stark commented on src/paymentPreview/utilityPreview.php
> +        - barCode [string]: Bar code number that identifies the payment. ex: "85660000006679400640074119002551100010601813"
parece que veio do tax isso em vez de utility

2021-08-31 19:38 UTC, cdottori-stark commented on tests/paymentRequest.php
> +// echo " - OK";
o.O

2021-09-01 14:44 UTC, cdottori-stark requested changes

2021-09-01 14:44 UTC, cdottori-stark commented on README.md
> +### Preview payment information before executing the payment
acho que faltou tirar o brcode preview do README, nao?

2021-09-01 14:47 UTC, massaru-stark commented on src/init.php
> +require_once(__DIR__."/paymentPreview/paymentPreview.php");
Funcionou normalmente

2021-09-01 16:21 UTC, cdottori-stark approved these changes

2021-09-01 16:21 UTC, merged