Change to use Starkcore as dependency
starkbank/sdk-php pull request #57
Opened 2022-09-16 22:35 UTC by delsonb-stark

2022-10-10 21:59 UTC, xavier-stark requested changes

2022-10-10 21:59 UTC, xavier-stark commented on src/utilityPayment/log.php
> +
Retirar essa linha

2022-10-10 21:59 UTC, xavier-stark commented on src/invoice/log.php
> +
Remover linha, apenas para padronização

2022-10-10 21:59 UTC, xavier-stark commented on src/init.php
> -require_once(__DIR__."/taxPayment/log.php");
Não precisa mais dos require_once?

2022-10-10 21:59 UTC, xavier-stark commented on src/event/attempt.php
Consegue tirar essa linha também?

2022-10-10 21:59 UTC, xavier-stark commented on src/error.php
> +class StarkError extends \StarkCore\Error\StarkError {};
Consegue fazer essa parte utilizando o using?

using StarkCore\Error etc...

2022-10-10 21:59 UTC, xavier-stark commented on src/deposit/log.php
> +
Remover linha apenas para padronização

2022-10-10 21:59 UTC, xavier-stark commented on src/deposit/deposit.php
>  class Deposit extends Resource
Consegue adicionar uma linha aqui?

2022-10-10 21:59 UTC, xavier-stark commented on src/darfPayment/log.php
> +
Remover linha apenas para padronização

2022-10-10 21:59 UTC, xavier-stark commented on src/brcodePreview/brcodePreview.php
> -use urlencode\urlencode;
Não precisa mais dessa linha?

2022-10-10 21:59 UTC, xavier-stark commented on src/boletoHolmes/log.php
> +
Remover linha apenas para padronização

2022-10-10 21:59 UTC, xavier-stark commented on src/boletoPayment/log.php
> +
Remover linha apenas para padronização

2022-10-10 21:59 UTC, xavier-stark commented on src/brcodePayment/log.php
> +
Remover linha apenas para padronização

2022-10-10 21:59 UTC, xavier-stark commented on src/invoice/payment.php
Consegue remover essa linha?

2022-10-10 21:59 UTC, xavier-stark commented on src/paymentPreview/boletoPreview.php
> +
Remover linha apenas para padronização

2022-10-10 21:59 UTC, xavier-stark commented on src/paymentPreview/brcodePreview.php
> +
Remover linha apenas para padronização

2022-10-13 20:32 UTC, delsonb-stark commented on src/init.php
> -require_once(__DIR__."/taxPayment/log.php");
Como o autoload tá configurado, não precisa chamar todos os arquivos explicitamente mais

2022-10-13 20:35 UTC, delsonb-stark commented on src/error.php
> +class StarkError extends \StarkCore\Error\StarkError {};
Daria pra fazer, mas pra evitar conflitos entre os nomes das classes, teríamos que definir um alias pra cada uma das classes. Infelizmente não deu certo fazer um import de todos os erros simultaneamente

2022-10-13 20:43 UTC, delsonb-stark commented on src/brcodePreview/brcodePreview.php
> -use urlencode\urlencode;
A função já fica disponível sem necessitar do import. O vscode tava apontando que esse import não estava sendo usado, então acabei removendo.

2022-10-24 19:20 UTC, xavier-stark approved these changes

2022-10-24 21:55 UTC, cdottori-stark requested changes

2022-10-24 21:55 UTC, cdottori-stark commented on CHANGELOG.md
> +- structure to use starkcore as a dependency.
"internal structure" talvez?

2022-10-24 21:55 UTC, cdottori-stark commented on src/setting.php
> +    public const sdkVersion = "v2.8.4";
Não é melhor deixar isso no relay direto? Aqui sugere que o usuário vai poder editar, nao?

2022-10-24 21:55 UTC, cdottori-stark commented on src/utils/relay.php
> +}
precisa mesmo dessa classe?

2022-10-25 20:37 UTC, closed without merging